server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: feed-hub
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/feedhub_development}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DATASOURCE_DBCREATE:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
jwt:
  secret:
    key: ${SECRET_KEY:4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P}
    issuer: ${ISSUER:feedhub}
    validity: ${VALIDITY:3600000}
