name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Application JAR
      run: mvn clean package

    - name: Docker Compose Build Application JAR
      run: docker compose build 
      
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag feed-hub:latest ${{ secrets.DOCKER_USERNAME }}/feed-hub-app:${{ github.run_id }}
        docker tag feed-hub:latest ${{ secrets.DOCKER_USERNAME }}/feed-hubt-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/feed-hub-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/feed-hub-app:latest
